### ISSUE TITLE
Environment YAML for Compute doesn't work out of the box

### ISSUE THREAD

**Issue by B0r1sD** [saeyslab/harpy#84]
Hi Harpy maintainers

Data Core checks every 3 months if the usage example to use Harpy on the Compute Cluster is working as intended. As you have excellent documentation on this, the strategy we discussed together was that we basically referred to your docs ([this part](https://harpy.readthedocs.io/en/latest/tutorials/hpc/vib_compute.html)) so they have the latest changes.

After rerunning the example with release 0.0.2, it didn't work out of the box. The following was seen and done to make it work:

1. The [environment_vib_compute.yml](https://harpy.readthedocs.io/en/latest/_downloads/70500549e1514fff22433d1404c97ee4/environment_vib_compute.yml) was pruned a bit too much I think, as I had to load the `jax/0.3.25-foss-2022a-CUDA-11.7.0` module in the Jupyter session + execute `python -m pip install textalloc spatialdata-plot` in the Harpy conda env to be able to load the Python libraries successfully. 

   The error after running cell one was the following (for traceback):
   ![image](https://github.com/user-attachments/assets/589d108e-3ec0-413c-8234-e04b71f69690)

2. The versions of the dependencies for the Conda env are not locked. This failed for a repo clone of the older version,so I can share the versions that were used previously that can help with this (which I tested):
 ```yml
 name: harpy
channels:
  - conda-forge
dependencies:
  - python=3.10.8
  - opencv=4.10.0
  - pip=24.3.1
  - rasterio=1.4.1
  - pip:
      - basicpy==1.0.0
      - torch==2.4.1
      - cellpose==3.0.11
      - jax==0.4.6
      - jaxlib==0.4.6
      - ipython==8.28.0
      - ipykernel==6.29.5
 ```

3. The plots on Compute somehow never get rendered if the magic command `%matplotlib inline` isn't ran before any plots are executed. This might be Compute specific, but as it's not clear why this is necessary, I'll open a pull request to add it to the notebook that is being referred in the docs (Harpy_feature_calculation.ipynb). 

We have a PR ready to merge to make [the usage example](https://docs.datacore.vib.be/usage-examples/spatial-harpy-sparrow) even more future proof, relying entirely on your documentation. We can keep you posted on the usability of the part were users could run Harpy on Compute, the same way I did here. 

Let me know your thoughts! 
Boris D
